name: Jekyll Themes
url: https://eenimeeniminimo.github.io
baseurl : ""
description: Insert tagline here
remote_theme : mattvh/jekyllthemes

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
